export const cars = [
  {
    id: 1,
    model: "G30",
    mark: "BMW",
    year: 2019,
    doors: "4/5",
    ac: "Yes",
    transmission: "Mechanical",
    fuel: "Diesel",
    images: "/G30.png",
    price: "$50",
  },
  {
    id: 2,
    model: "Q7",
    mark: "Audi",
    year: 2017,
    doors: "4/5",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Petrol",
    images: "/RS6.png",
    price: "$48",
  },
  {
    id: 3,
    model: "Camry",
    mark: "Toyota",
    year: 2012,
    doors: "4/5",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Petrol",
    images: "/Camry-1.png",
    price: "$35",
  },
  {
    id: 4,
    model: "Golf 6",
    mark: "Volkswagen",
    year: 2010,
    doors: "2/3",
    ac: "Yes",
    transmission: "Mechanical",
    fuel: "Petrol",
    images: "/Golf 6.png",
    price: "$30",
  },
  {
    id: 5,
    model: "GLK",
    mark: "Mercedes",
    year: 2017,
    doors: "4/5",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Diesel",
    images: "/GL.png",
    price: "$43",
  },
  {
    id: 6,
    model: "911",
    mark: "Porsche",
    year: 2020,
    doors: "2/3",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Petrol",
    images: "/911.png",
    price: "$78",
  },
];
